@localURL = http://localhost:3000/api
@prodURL = http://mtg.justingajitos.com/api
@username = chosenone

###

# GET {{localURL}}/users HTTP/1.1
GET {{prodURL}}/users HTTP/1.1

###

# POST {{localURL}}/users HTTP/1.1
POST {{prodURL}}/users HTTP/1.1
Content-Type: application/json

{
	"user": {
		"username": "{{username}}",
		"firstName": "Harry",
		"lastName": "Potter",
		"password": "ginnyweasley"
	}
}

###

# GET {{localURL}}/users/{{username}} HTTP/1.1
GET {{prodURL}}/users/{{username}} HTTP/1.1

###

# PUT {{localURL}}/users/{{username}} HTTP/1.1
PUT {{prodURL}}/users/{{username}} HTTP/1.1
Content-Type: application/json

{
	"user": {
		"username": "{{username}}",
		"firstName": "Harry",
		"lastName": "Potter",
		"password": "ginervaweasley"
	}
}

###

# DELETE {{localURL}}/users/{{username}} HTTP/1.1
DELETE {{prodURL}}/users/{{username}} HTTP/1.1

###

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
	"user": {
		"username": "gaji",
		"password": "gajigaji"
	}
}

###