@root = http://localhost:5000/api/v1
@endpoint = /users
@URL = {{root}}/{{endpoint}}

###

GET {{URL}} HTTP/1.1

###

POST {{URL}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "hifumin",
    "firstName": "Hifumi",
    "lastName": "Takimoto",
    "password": "hedgehog"
  }
}

###

POST {{URL}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "aocchi",
    "firstName": "Aoba",
    "lastName": "Suzukaze",
    "password": "nenecchi"
  }
}

###

POST {{URL}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "kochan",
    "firstName": "Kou",
    "lastName": "Yagami",
    "password": "tooyamar"
  }
}

###

GET {{URL}}/hifumin HTTP/1.1

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "firstName": "Aoba"
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "dateRegistered": "1999-12-31T11:22:33.656Z"
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "_id": "111111111111222222222222"
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "theme": "swamp"
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "userRooms": [
      {
        "roomId": 3
      }
    ]
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "poison": 500
    }
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "life": 100
    }
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "land": {
        "plains": 500
      }
    }
  }
}

###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "land": {
        "plains": 1,
        "island": 2,
        "swamp": 3,
        "mountain": 4,
        "forest": 5
      },
      "life": 17,
      "poison": 4
    }
  }
}
###

PUT {{URL}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "firstName": "Hifumi",
    "theme": "plains",
    "counter": {
      "poison": 0,
      "land": {
        "island": 200
      }
    }
  }
}

###

DELETE {{URL}}/hifumin HTTP/1.1
