@hostname = http://localhost
@port = 5000
@version = v1
@endpoint = /users
@baseUrl = {{hostname}}:{{port}}/api/{{version}}
@contentType = application/json

###

GET {{baseUrl}}/{{endpoint}} HTTP/1.1

###

POST {{baseUrl}}/{{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "hifumin",
    "firstName": "Hifumi",
    "lastName": "Takimoto",
    "password": "hedgehog"
  }
}

###

POST {{baseUrl}}/{{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "aocchi",
    "firstName": "Aoba",
    "lastName": "Suzukaze",
    "password": "nenecchi"
  }
}

###

POST {{baseUrl}}/{{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "user" : {
    "username": "kochan",
    "firstName": "Kou",
    "lastName": "Yagami",
    "password": "tooyamar"
  }
}

###

GET {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1

###

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "firstName": "Aoba"
  }
}

###

# Invalid PUT request

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "dateRegistered": "1999-12-31T11:22:33.656Z"
  }
}

###

# Invalid PUT request

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "_id": "111111111111222222222222"
  }
}

###

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "theme": "swamp"
  }
}

###

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "userRooms": [
      {
        "roomId": 3
      }
    ]
  }
}

###

# Bug - reverts other values in the counter object to their default values

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "poison": 500
    }
  }
}

###

# Bug - reverts other values in the counter object to their default values

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "life": 100
    }
  }
}

###

# Bug - reverts other values in the counter object to their default values

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "land": {
        "plains": 500
      }
    }
  }
}

###

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "counter": {
      "land": {
        "plains": 1,
        "island": 2,
        "swamp": 3,
        "mountain": 4,
        "forest": 5
      },
      "life": 17,
      "poison": 4
    }
  }
}
###

# Bad Request - should send complete counter object

PUT {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
Content-Type: application/json

{
  "user": {
    "firstName": "Hifumi",
    "theme": "plains",
    "counter": {
      "poison": 0,
      "land": {
        "island": 200
      }
    }
  }
}

###

DELETE {{baseUrl}}/{{endpoint}}/hifumin HTTP/1.1
