export const MANIPULATE_SINGLE_COUNTER = 'MANIPULATE_SINGLE_COUNTER';
export const MANIPULATE_LAND_COUNTER = 'MANIPULATE_LAND_COUNTER';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const SET_MODE = 'SET_MODE';
export const GET_USER = 'GET_USER';
export const USER_LOADING = 'USER_LOADING';
