export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const GET_USER = 'GET_USER';
export const USER_LOADING = 'USER_LOADING';
